
services:
  - docker:dind
image: docker
before_script:
  - apk add --update py-pip
  - pip install docker-compose
  - sudo docker image prune -f
  - docker info

build:
  stage: build
  script: - docker-compose build --no-cache
  only:
  - master

test:
  stage: test
  script: docker-compose run path-of-test  {Please attention that I didn't enough time to write test}
  only:
  - merge_requests

deploy:
  stage: deploy
  script:
    - sudo docker image prune -f
    - docker-compose build --no-cache
    - docker-compose up -d  # or - some-deploy-script.sh --with args
  only:
  - master